version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:0.8.2-pg16-bookworm
    container_name: school_db
    environment:
      POSTGRES_DB: school_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    command: ["postgres", "-c", "shared_preload_libraries=vector"]
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: school_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/school_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: school_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: