spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/school_db
spring.datasource.username=school_user
spring.datasource.password=school_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.mvc.cors.allowed-origins=*
spring.mvc.cors.allowed-methods=*
spring.mvc.cors.allowed-headers=*

server.port=8080